### ISSUE TITLE
 TrendsPage: Unable to locate element: {"method":"css selector","selector":"#input\-254"}

### ISSUE THREAD

**Issue by sergiiil-tr** [MarianaMat/GoogleTrends_UITests#1]
https://github.com/MarianaMat/GoogleTrends_UITests/blob/01699ee26001d9bfe384ccb47a1ceb20591a9e01/GoogleTrends_UITests/PageObjects/TrendsPage.cs#L35

Looks like for some reason #input-254 is not relevant anymore and the test fails
![image](https://user-images.githubusercontent.com/46960191/87313699-f2bd1e00-c52a-11ea-9be5-606f2b5ec4f0.png)

**Comment by MarianaMat** [comment]
Fixed.

**Comment by sergiiil-tr** [comment]
works now, thanks!
